/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module gen_map_19 (
    input clk,
    input rst,
    output reg out
  );
  
  
  
  always @* begin
    out = 25'h0000010;
  end
endmodule
