/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module toggle_map_20 (
    input clk,
    input rst,
    input [24:0] current_map,
    input [24:0] current_cursor,
    output reg completed,
    output reg out
  );
  
  
  
  always @* begin
    completed = 1'h0;
    if (current_map == 25'h0000000) begin
      completed = 1'h1;
    end
    out = current_map + current_cursor;
  end
endmodule
