/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module gen_map_temp_19 (
    input clk,
    input rst,
    output reg [24:0] out
  );
  
  
  
  always @* begin
    out = 25'h0000800;
  end
endmodule
